var User

User = (function () {
  function User (id, options) {
    var k
    this.id = id
    if (options == null) {
      options = {}
    }
    for (k in options || {}) {
      this[k] = options[k]
    }
    this['name'] || (this['name'] = this.id.toString())
  }

  return User
})()

module.exports = User

// ---
// generated by coffee-script 1.9.2
